showfavourites: false
version: ""
feeds:
    - url: https://www.euro2day.gr/rss.ashx?catid=139
    - url: https://nixos.org/blog/newsletters-rss.xml
    - url: https://nixos.org/blog/stories-rss.xml
theme:
    glamour: dark
    titleColor: "62"
    filterColor: "62"
    selectedItemColor: "170"
http:
    mintls: TLS 1.2
