import = ["~/.config/alacritty/everforest.toml"]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "Fira Code"
# family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
# family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
# family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Fira Code"
# family = "Hack Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "R"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.95

[window.dimensions]
columns = 130
lines = 50

[window.padding]
x = 5
y = 5
