# specify read only file
read: [~/dot/aider/CONVENTIONS.md, ~/dot/aider/git_conventions.md]

# Main model settings
# model: "vertex_ai/gemini-2.0-flash-thinking-exp"
# opus: ""
# sonnet: ""
# haiku: ""
# 4: ""
# 4o: ""
# mini: ""
# turbo: ""
# deepseek: ""
# o1_mini: ""
# o1_preview: ""

# API keys and settings
# Safer to pass them as env variables
# openai-api-key: ""  # Add API key here if needed
# openai-api-base: ""  # API base URL if needed
# anthropic-api-key: ""  # Add API key here if needed

# Model settings
architect: true
verify-ssl: true
show-model-warnings: true
model-settings-file: .aider.model.settings.yml
model-metadata-file: .aider.model.metadata.json
# model: # the main model
# editor-model: # the editor model aka the `coding` model
# max-chat-history-tokensl 10000  # Optional setting for max chat history tokens
# timeout: 10_000  # Optional timeout setting

# Cache settings
cache-prompts: true
# cache-keepalive-pings: 0

# Repo map settings
map-refresh: auto
# map_multiplier_no_files: true

# History files
input-history-file: .aider.input.history
chat-history-file: .aider.chat.history.md
restore-chat-history: false
# llm-history-file: ""

# Output settings
dark-mode: true
light-mode: false
pretty: true
stream: true
# code-theme: zenburn
show-diffs: true

# Git settings
git: true
gitignore: true
aiderignore: .aiderignore
subtree-only: true
auto-commits: true
dirty-commits: true
attribute-author: false # no (Aider) next to author name
attribute-committer: false # no (Aider) next to the committer name
# commit-prompt: Write concise, descriptive commit messages with a clear header (50 chars max) that ends with (A), optional body (72 chars/line), using specific prefixes, and referencing issues when relevant.
commit: false
dry-run: false
skip-sanity-check-repo: false
watch-files: false

# Fixing and committing
lint: false
# lint-cmd: "python: ruff check --fix"
auto-lint: false
# test-cmd: xxx  # Optional test command
auto-test: false
test: false

# Analytics
analytics-disable: true
# analytics-log:  # Optional analytics log file

# Upgrading
just-check-update: false
check-update: false
install-main-branch: false
upgrade: false

# Modes
gui: false
copy-paste: false
exit: false

# Voice settings
# voice-format: wav
# voice-language: en

# Other settings
vim: true
yes-always: false
verbose: false
encoding: utf-8
suggest-shell-commands: true
fancy-input: true
multiline: false
detect-urls: true
