# Configure the format of the prompt
format = """
$username\
$hostname\
$directory\
$sudo\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$gcloud\
$fill\
$jobs $python $rust $cmd_duration $time\
$line_break\
$status\
$character
"""

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 750
# Timeout for starship to scan files (in milliseconds)
scan_timeout = 50
# Add a new line before the start of the prompt
add_newline = true

[fill]
disabled = false
symbol = " "

[character]
disabled = false
format = "$symbol "
# success_symbol = "[->](bold green)"
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[cmd_duration]
disabled = false
min_time = 2_000
format = '\[[tt: $duration]($style)\]'
show_milliseconds = true
show_notifications = false
min_time_to_notify = 5_000

[directory]
disabled = false
truncation_length = 4
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true
read_only = "  "
read_only_style = "fg:red"
truncation_symbol = "../"

[gcloud]
disabled = false
format = '([\[$symbol\]]($style))'
symbol = " "

[git_branch]
disabled = false
style = "bright-black"
format = '([\[$symbol$branch\]]($style)) '
symbol = " "
truncation_symbol = "…"
# truncation_length = 7 # default = 2^63 - 1

[git_commit]
disabled = false
commit_hash_length = 7
format = '([\[$symbol$has\]]($style))'
# format = '\[[$hash\]($style)\]'
only_detached = true

[git_state]
disabled = true
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
format = '\[[$state]($style)\]'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style)) '
#stashed = '\$'
stashed = ''
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
conflicted = "="
deleted = "✘"
renamed = "»"
modified = "!"
staged = "+"
untracked = "?"

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style))'

[hostname]
disabled = false
ssh_only = true
trim_at = "."
format = '\[[$symbol($hostname)]($style)\]'

[jobs]
disabled = false
symbol = "+ "
symbol_threshold = 1
number_threshold = 2
format = '[[$symbol($number)]($style)]'

[line_break]
disabled = false

[python]
disabled = false
pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
style = "blue bold"
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
# symbol = " "
symbol = " "

[rust]
disabled = false
style = "red bold"
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[status]
disabled = false
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
# format = "[[]$symbol$status[]]($style)"
symbol = "🚫 "
# symbol = " ✖"

[sudo]
disabled = true
format = '\[[$symbol($version)]($style)\]'
symbol = ""

[time]
disabled = false
format = '\[[$time]($style)\]'
# time_format = "%R"
utc_time_offset = "local"
time_range = "-"

[username]
disabled = false
format = '\[[$user]($style)\]'
style_root = "bold bg:#555555 fg:red"
style_user = "bold bg:#555555 fg:yellow"
show_always = false
