theme = "catppuccin_mocha"

[editor]
idle-timeout = 50
true-color = true
color-modes = true
mouse = false
cursorline = true
bufferline = "multiple"
rulers = [120]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[keys.insert]
# j = { k = "normal_mode" }

[keys.normal]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"
W = "extend_next_word_start"
B = "extend_prev_word_start"
E = "extend_next_word_end"
"#" = "toggle_comments"
"left" = "goto_previous_buffer"
"right" = "goto_next_buffer"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[editor.indent-guides]
render = true
character = "╎"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "position", "position-percentage", "file-type"]
separator = "│"

