theme = "everforest_dark"
# theme = "boo_berry"
# theme = "ferra"
# theme = "hex_toxic"
# theme = "rose_pine"

[editor]
auto-save = true
bufferline = "multiple"
color-modes = true
completion-replace = true
cursorline = true
idle-timeout = 25
mouse = false
rulers = [120]
scrolloff = 10
true-color = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = [
  "version-control",
  "position",
  "position-percentage",
  "total-line-numbers",
  "file-type",
]
separator = "│"

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
# insert = "block" # works better for rose-pine
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
rainbow-option = "normal"
# character = "╎"
character = "┆"
# character = "┊"
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.insert]
# j = { k = "normal_mode" }

[keys.normal]
"esc" = ["normal_mode", ":format", ":write"] # For quick saving
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"
W = "extend_next_word_start"
B = "extend_prev_word_start"
E = "extend_next_word_end"
X = "extend_line_above"
G = "goto_file_end"
"#" = "toggle_comments"
"left" = "goto_previous_buffer"
"right" = "goto_next_buffer"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
C-o = ":config-open"
C-r = [":w", ":config-reload"]
D = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]

# CONFLICT: 
# c + shift is used for something else
# C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]

# EXPERIMENT:
# I like for moving selected text up/down and left/right:
# Userd Alt key but it seems there was a conflict with Alt key used by alacritty
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
# C-l = ["delete_selection", "move_char_right", "paste_after"]
# CONFLICT:
# C-h = ["delete_selection", "move_char_left", "paste_before"]

# EXPERIMENT:
# in normal mode, press space and c and then the keys below
[keys.normal.space.c]
r = [":w", ":config-reload"]
o = ":config-open"
