theme = "catppuccin_mocha"

[editor]
idle-timeout = 100
true-color = true
mouse = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[keys.insert]
# j = { k = "normal_mode" }

[keys.normal]
W = "extend_next_word_start"
B = "extend_prev_word_start"
"left" = "goto_previous_buffer"
"right" = "goto_next_buffer"
"#" = "toggle_comments"
# "{" = "move_prev_paragraph" # doesnt exist yet
# "}" = "move_next_paragraph"

# [editor.whitespace]
# render = "all"
# or control each character
[editor.whitespace.render]
tab = "all"
space = "none"
newline = "none"

[editor.whitespace.characters]
tab = "→"
space = " "
newline = "⏎"
nbsp = "⍽"
