theme = "varua"

[editor]
idle-timeout = 50
true-color = true
color-modes = true
mouse = false
cursorline = true
bufferline = "multiple"
rulers = [120]
scroll-lines = 5
auto-save = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = ["position", "position-percentage", "total-line-numbers", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
# character = "╎"
character = "┆"
# character = "┊"

[keys.insert]
# j = { k = "normal_mode" }

[keys.normal]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"
W = "extend_next_word_start"
B = "extend_prev_word_start"
E = "extend_next_word_end"
C-o = ":open ~/.config/helix/config.toml"
"#" = "toggle_comments"
"left" = "goto_previous_buffer"
"right" = "goto_next_buffer"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
