theme = "rose_pine"

[editor]
auto-save = true
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 50
mouse = false
rulers = [120]
scroll-lines = 5
true-color = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "file-modification-indicator"]
right = [
  "version-control",
  "position",
  "position-percentage",
  "total-line-numbers",
  "file-type",
]
separator = "│"

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
normal = "block"
# insert = "bar"
insert = "block"     # works better for rose-pine
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
rainbow-option = "normal"
render = true
# character = "╎"
character = "┆"
# character = "┊"
skip-levels = 1

[keys.insert]
# j = { k = "normal_mode" }

[keys.normal]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"
W = "extend_next_word_start"
B = "extend_prev_word_start"
E = "extend_next_word_end"
X = "extend_line_above"
G = "goto_file_end"
"#" = "toggle_comments"
"left" = "goto_previous_buffer"
"right" = "goto_next_buffer"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
C-o = ":config-open"
C-r = [":w", ":config-reload"]
# CONFLICT: c + shift is used for something else
# C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]

# EXPERIMENT:
# in normal mode, press space and c and then the keys below
[keys.normal.space.c]
r = [":w", ":config-reload"]
o = ":config-open"
