[default]
extend-ignore-identifiers-re = ["splitted.*"]

[default.extend-words]
ACTIV = "ACTIV"
Bund = "Bund"
OT = "OT"
Maks = "Maks"
NDFs = "NDFs"
ND = "ND"
WTH = "WTH"
ue = "ue"

[files]
extend-exclude = ["*.csv", "*.ini"]
