#!/bin/sh

grep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

## control gaps and top bar
gap=5
PANEL_HEIGHT=10
export gap
export PANEL_HEIGHT
bspc config window_gap                $gap;
# need this for the polybar at the top
bspc config top_padding               $(($PANEL_HEIGHT-$gap))
bspc config left_padding              $gap
bspc config right_padding             $gap
bspc config bottom_padding            $gap

bspc config gapless_monocle           false
bspc config borderless_monocle        true
bspc config single_monocle            true
bspc config paddingless_monocle       false
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer     true

## color settings
bspc config focused_border_color      "#ffb300"
bspc config normal_border_color       "#6d4c41"
# bspc config presel_feedback_color   "#1ABB9B"
bspc config border_width              2
bspc config split_ratio               0.52

# monitors
# this creates and names desktops for multiple monitors.
workspaces_multimonitor &
# current setup (arch linux)
# DP left
bspc monitor DP-0 -d 1 2 3 4 5
# HDMI right
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc rule -a firefox private=on
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled

xsetroot cursor_name left_ptr
