jcomplete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
filesize_format = "mb"
filesize_metric = true
nonzero_exit_errors = true
pivot_mode = "auto"
# start starship
prompt = "STARSHIP_SHELL= starship prompt"
rm_always_trash = true
skip_welcome_message = true
table_mode = "compact"
# import all the paths
path = [
  "~/.local/share/nvim/lsp_servers", 
  "~/.local/share/cargo/bin", 
  "/usr/local/opt/python/libexec/bin", 
  "~/.local/bin", 
  "~/dot/scripts", 
  "/usr/local/sbin", 
  "/usr/local/bin", 
  "/usr/bin"]
startup = [
  # EXPERIMENTS
  # "def l [] {ls -la | sort-by size | select name type num_links mode size modified}", 
  # "alias lf = ls | where type == file", 

  # Aliases - general shortcuts/improvements
  "alias .. = cd ..", 
  "alias ... = cd ../../", 
  "alias c = clear", 
  "alias ssd = sudo shutdown now", 
  "alias sr = sudo reboot", 
  "alias clock = tock -cms", 
  # with -i it is asking you if overwrites something
  # with -v it explains what is being done on terminal - visual
  # with -p you are making the parent directory if doesnt exist
  "alias mkdir = mkdir -pv",
  "alias rmd = rm -rfv", 
  "alias rm = rm -iv", 
  "alias mv = mv -iv", 
  "alias cp = cp -iv", 
  "alias cat = bat", 
  "alias p = python", 
  "alias b = bash", 
  "alias v = ~/.local/bin/lvim", 

  # PYTHON-PIP
  # find the version for each python program installed using fzf
  "def pipv [] {pip list | fzf}",

  # PACMAN - PARU SCRIPTS
  # install pacman program with the help of fzf
  "def pi [] {pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S}",
  # remove pacman program with the help of fzf
  "def pr [] {pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns}",
  # find the version for each pacman program install using fzf
  "def pv [] {pacman -Q | fzf}",
  # install arch + aur programs with the help of paru and fzf
  "def auri [] {paru -Slq | fzf --multi --preview 'paru -Si {1}' | xargs -ro paru -S}",

  # RUST
  # cargo shortcuts
  # https://doc.rust-lang.org/book/ch01-03-hello-cargo.html
  "alias cc = cargo check",
  "alias cr = cargo run",
  "alias cb = cargo build",
  "alias cn = cargo new",
  "alias ci = cargo install",
  "alias cc = cargo check",
  "alias cr = cargo run",
  "alias cb = cargo build",
  "alias cs = cargo search",
  "alias cu = cargo install-update -a",
  "alias cl = cargo install-update -l",
  # exa shortcuts
  # https://the.exa.website/docs/command-line-options
  "alias l = exa -alh --colour=always --sort=ext --icons",
  "alias lld = exa -alh --colour=always --group-directories-first --icons", # sort by directory first
  "alias lls = exa -alh --colour=always --group-directories-first --sort=size --icons", # sort by size
  "alias lln = exa -alh --colour=always --group-directories-first --sort=name --icons", # sort by size
  # dust shortcuts
  # https://github.com/bootandy/dust
  "alias d = d() { dust -n $1 ;},d",

  # GIT SHORTCUTS
  "alias gc = nu git_commit_workflow.nu",
  "alias ginit = git_init_template.sh",
  "alias glg = git_log_graph.sh",
  "alias gpulla = git_pull_all_git_dirs.sh",
  "alias gsa = git_status_all_git_dirs.sh",
  # amend a commit without changing the commit message
  "alias gcane = git commit --amend --no-edit",
  "alias gd = git diff",
  "alias gl = git log",
  "alias glo = git log --oneline",
  "alias gs = git status -sb",
  "alias lg = lazygit",]

[color_config]
header_align = "l"
header_bold = true
header_color = "c"
index_color = "rd"
leading_trailing_space_bg = "white"
primitive_binary = "cyan"
primitive_boolean = "green"
primitive_columnpath = "cyan"
primitive_date = "red"
primitive_decimal = "red"
primitive_duration = "blue"
primitive_filesize = "blue"
primitive_int = "green"
primitive_line = "yellow"
primitive_path = "yellow"
primitive_pattern = "white"
primitive_range = "purple"
primitive_string = "pb"
separator_color = "purple"

[env]
ALACRITTY_LOG = "/tmp/Alacritty-4418.log"
BROWSER = "firefox"
CARGO_HOME = "/home/jokyv/.local/share/cargo"
CMD_DURATION_MS = "8"
COLORTERM = "truecolor"
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
DISPLAY = ":0"
EDITOR = "lvim"
FZF_ALT_C_COMMAND = "fd -td . /home/jokyv"
FZF_CTRL_T_COMMAND = "fd . /home/jokyv"
FZF_DEFAULT_COMMAND = "fd . /home/jokyv"
FZF_DEFAULT_OPTS = "--layout=reverse --height 40%"
GNUPGHOME = "/home/jokyv/.local/share/gnupg"
GTK_MODULES = "canberra-gtk-module"
HISTFILE = "/home/jokyv/.local/share/bash/history"
HOME = "/home/jokyv"
INVOCATION_ID = "e3bd2d94c5094fbd8eb299726ec662ab"
JOURNAL_STREAM = "8:17158"
LANG = "en_US.UTF-8"
LESSHISTFILE = "-"
LOGNAME = "jokyv"
MAIL = "/var/spool/mail/jokyv"
MOTD_SHOWN = "pam"
OLDPWD = "/home/jokyv/projects/rust_book_notes/chapter_7_packages_crates_modules/restaurant/src"
PWD = "/home/jokyv"
PYLINTHOME = "/home/jokyv/.local/share/pylint"
PYTHONPATH = ":/home/jokyv/projects/python_path:/home/jokyv/projects/python_path"
RUSTUP_HOME = "/home/jokyv/.local/share/rustup"
SHELL = "/bin/bash"
SHLVL = "3"
STARSHIP_SESSION_KEY = "2720932582176042"
STARSHIP_SHELL = "bash"
SYSTEMD_EXEC_PID = "511"
TERM = "alacritty"
TERMINAL = "alacritty"
USER = "jokyv"
VISUAL = "lvim"
WINDOWID = "6291463"
WINDOWPATH = "1"
WM = "bspwm"
XAUTHORITY = "/home/jokyv/.Xauthority"
XDG_CACHE_HOME = "/home/jokyv/.cache"
XDG_CONFIG_HOME = "/home/jokyv/.config"
XDG_RUNTIME_DIR = "/run/user/1000"
XDG_SEAT = "seat0"
XDG_SESSION_CLASS = "user"
XDG_SESSION_ID = "1"
XDG_SESSION_TYPE = "tty"
XDG_VTNR = "1"
XGD_DATA_HOME = "/home/jokyv/.local/share"
XINITRC = "/home/jokyv/.config/X11/xinitrc"
_ = "/home/jokyv/.local/share/cargo/bin/nu"

[line_editor]
auto_add_history = true
bell_style = "audible"
color_mode = "enabled"
completion_prompt_limit = 100
completion_type = "circular"
edit_mode = "lvim"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 100000
tab_stop = 4

[textview]
colored_output = true
grid = false
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"
