#!/usr/bin/env python
# By using env you make sure that the system finds python and delegates the script's execution to it

import sys
import scipy
import numpy
import pandas
import matplotlib
import sklearn
import lightgbm as lgb
import optuna


def print_versions():
    print("versions:")
    print(f"python: {sys.version}")
    print(f"scipy: {scipy.__version__}")
    print(f"numpy: {numpy.__version__}")
    print(f"pandas: {pandas.__version__}")
    print(f"matplotlib: {matplotlib.__version__}")
    print(f"sklearn: {sklearn.__version__}")
    print(f"LightGBM: {lgb.__version__}")
    print(f"optuna: {optuna.__version__}")


print_versions()
